version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - db.host=database
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
      - resolute_rabbitmq_publishQueueName=resolute-run-request
      - resolute_rabbitmq_exchange=resolute

  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bankcore
      - POSTGRES_PASSWORD=bankcore
      - POSTGRES_DB=bankcore

  rabbitmq:
    image: rabbitmq:3.9.16-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
